global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'model-serving'
    static_configs:
      - targets: ['model-serving:8000']
    metrics_path: '/metrics'

  - job_name: 'order-router'
    static_configs:
      - targets: ['order-router:80']
    metrics_path: '/metrics'

  - job_name: 'kafka-streams'
    static_configs:
      - targets: ['kafka-streams:8080']
    metrics_path: '/metrics'

  - job_name: 'paper-trading'
    static_configs:
      - targets: ['paper-trading:8001']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']